//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danilov_stadium
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_statuses
    {
        public decimal status_record_id { get; set; }
        public decimal event_id { get; set; }
        public Nullable<decimal> status_id { get; set; }
        public Nullable<decimal> participant1 { get; set; }
        public Nullable<decimal> participant2 { get; set; }
        public Nullable<decimal> winner { get; set; }
    
        public virtual statuses statuses { get; set; }
        public virtual teams teams { get; set; }
        public virtual teams teams1 { get; set; }
        public virtual teams teams2 { get; set; }
    }
}
