//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Danilov_stadium
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_sets
    {
        public decimal record_id { get; set; }
        public decimal event_id { get; set; }
        public decimal staff_id { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual events events { get; set; }
        public virtual staff staff { get; set; }
    }
}
